config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'api/users' => 'users#index'
  get 'api/c_user' => 'users#c_user'
  get 'api/reply/:id' => 'replies#c_reply'
  get 'replies' => 'replies#index'
  get "profile/:id"=> "users#profile"

  resources :requests do
    resources :replies do
      post :choose, on: :member
      resources :reviews
    end
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
  has_one :review
  has_many :pictures, dependent: :destroy

  def find_user(user_id)
    @username = User.find(user_id).username
  end

  def set_chosen
    self.chosen = true
    self.save
    self.request.resolved = true
    self.request.save
  end

  def message
    message = "Your tour has been chosen, please visit /replies"
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  before_filter :authenticate_user!

  def c_reply
    reply = Reply.find(params[:id])
    pics = reply.pictures.map(&:image_url)
    render json: pics.to_json
  end

  def index
    @replies = current_user.replies.all
  end

  def new
    @request = Request.find(params[:request_id])
    @reply = Reply.new
  end

  def create
    @request = Request.find(params[:request_id])
    @reply = @request.build_reply(reply_params, current_user)
    if @reply.save
      if params[:images]
        params[:images].each do |image|
          @reply.pictures.create(image: image)
        end
      end
      @request.set_expiration_date
      @request.save
      SmsHandler.new.send_you_have_reply(@request.user)
      redirect_to replies_path
    else
      if @reply.errors[:user]
        redirect_to requests_path
      else
        render :new
      end
    end
  end

  def choose
    @request = Request.find(params[:request_id])
    @reply = Reply.find(params[:id])
    @reply.set_chosen
    flash[:notice] = 'Reply chosen. Your tourguide will receive a text message notification.'
    SmsHandler.new.send_tour_accepted(@reply.user)
    redirect_to requests_path
  end

  def edit
    @request = Request.find(params[:request_id])
    @reply = Reply.find(params[:id])
  end

  def update
    @request = Request.find(params[:request_id])
    @reply = Reply.find(params[:id])
    if @reply.user_id == current_user.id
      @reply.update(reply_params)
    else
      flash[:notice] = 'Only owner can update replies'
    end
    redirect_to replies_path
  end

  def destroy
    @request = Request.find(params[:request_id])
    @reply = Reply.find(params[:id])
    if @reply.user_id == current_user.id
      @reply.destroy
      flash[:notice] = 'Request deleted successfully'
    else
      flash[:alert] = 'Only owner can delete request'
    end
    redirect_to replies_path
  end

  def reply_params
    params.require(:reply).permit(:meeting_point, :duration, :cost, :stopoffs, :description)
  end

end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
  <div class="col-sm-5 col-md-5">
    <%= form_for [@request, @reply], html: { class: 'form-horizontal', multipart: true } do |f| %>

    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-body">

    <div class="form-group">
      <%= f.label :meeting_point  %>
      <%= f.text_field :meeting_point, class: 'form-control', placeholder: 'Where do you want to meet?' %>
    </div>
    <div class="form-group">
      <%= f.label :duration %>
      <%= f.number_field :duration, min: 0, class: 'form-control',  placeholder: 'How long will the tour last?'  %>
    </div>
    <div class="form-group">
      <%= f.label :cost %>
      £<%= f.number_field :cost, min: 0, class: 'form-control', placeholder: "How much will you charge?" %>
    </div>
    <div class="form-group">
      <%= f.label :stopoffs %>
      <%= f.text_area :stopoffs, class: 'form-control', placeholder: "Which places will you visit?" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', placeholder: "Any extra information..." %>
    </div>
    <div class="form-group">
      <%= f.label :pictures, class: 'form-label' %>
      <div class="form-control">
        <%= file_field_tag "images[]", type: :file, multiple: true, id: 'replyPicsInp' %>
      </div>
    </div>
    <div id="replyPics" class="form-group container-fluid">
      <div class="form-group container-fluid">
        <img id="replyPicsOut1" src="" class="hidden" alt="your image" />
      </div>
    </div>
    <div class="modal-footer">
    <div class="actions">
      <%= f.submit 'Reply', class: 'btn btn-primary' %>
    </div>
  </div>
  </div>
</div>
</div>


    <% end %>
  </div>

app/views/replies/_single_reply.html.erb
<div class="paper">
  <div class="paper-container">
    <section class="left-side">
      <h5><span class="round-image-50"><%= image_tag(reply.user.avatar.url(:thumb)) %></span>
      <span><%= average_stars(reply.user.average_rating) %> (<%= reply.user.reviews.count %>)</span></h5>
      <h2><a href="/profile/<%=reply.user_id%>"><%= reply.user.username %></a></h2>
      <table>
        <tr>
          <td>Duration:</td>
          <td class="impt"><%= reply.duration %> hours</td>
        </tr>
        <tr>
          <td>Cost:</td>
          <td class="impt">£<%= reply.cost %></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td class="impt"><%= reply.description %></td>
        </tr>
        <tr>
          <td>Meeting point:</td>
          <td class="impt"><%= reply.meeting_point %></td>
        </tr>
        <tr>
          <td>Stopoffs:</td>
          <td class="impt"><%= build_stopoff_links(reply).html_safe %></td>
        </tr>
      </table>
      <br /><a href="<%= build_map_link(reply) %>" target="_blank" class='btn btn-primary'>Show in map</a><br />
      <% if reply.user == current_user %>
        <br />
        <%= link_to 'Update', edit_request_reply_path(request, reply) %>
        <%= link_to 'Delete', request_reply_path(request, reply), method: :delete %>
      <% end %>
      <% if request.user == current_user && !request.resolved %>
        <%= link_to 'Choose', choose_request_reply_path(request, reply), method: :post, class: 'btn btn-default' %>
      <% elsif request.user == current_user && request.resolved && reply.chosen %>
        <a href="#" data-toggle="modal" data-target="#reviewModal<%=reply.id%>" class='btn btn-default'>Leave a review</a>
        <%= render 'reviews/modal_review', request: request, reply: reply %>
        <br /><i class="fa fa-check"></i>
      <% elsif request.user == current_user && request.resolved && !reply.chosen %>
        <br /><i class="fa fa-times"></i>
      <% end %>
    </section>
     <section class="right-side">
       <div class="img-thumbnail" ng-controller="ReplyPicsController as rpCtrl">
         <div ng-init="rpCtrl.getImages(<%=reply.id%>)" ng-show="rpCtrl.showImages">
           <ng-gallery images="rpCtrl.images" thumbs-num="{{rpCtrl.images.length}}">
           </ng-gallery>
         </div>
       </div>
     </section>
   </div>
</div>

app/views/replies/edit.html.erb
<%= render "form" %>

app/views/replies/index.html.erb
<% if @replies.any? %>
  <div class="container comment-list">
    <% @replies.each do |reply| %>
      <div class="row">
        <div class="col-md-6 col-sm-6">
          <%= render 'single_reply', reply: reply, request: reply.request %>
        </div>
        <%= render 'requests/single_card', request: reply.request %>
      </div>
    <% end %>
  </div>
<% else %>
  <p> You have not made any replies yet. </p>
<% end %>

app/views/replies/new.html.erb
<%= render 'requests/single_card', request: @request %>

<%= render "form" %>