config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'api/users' => 'users#index'
  get 'api/c_user' => 'users#c_user'
  get 'api/reply/:id' => 'replies#c_reply'
  get 'replies' => 'replies#index'
  get "profile/:id"=> "users#profile"

  resources :requests do
    resources :replies do
      post :choose, on: :member
      resources :reviews
    end
  end

end

app/models/request.rb
class Request < ActiveRecord::Base

  belongs_to :user
  has_many :replies, dependent: :destroy
  before_create :set_expiration_date

  validates_presence_of :user
  validates_presence_of :request_date

  def set_expiration_date
    if self.replies.any?
      self.expiration =  self.request_date + 1000.days
    else
      self.expiration =  self.request_date + 5.days
    end
  end

  #should it expire when the date you requested to go on tour has passed?

  def build_reply(attributes = {}, user)
    attributes[:user] ||= user
    replies.build(attributes)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  respond_to :html, :json
  before_filter :authenticate_user!

  def index
    @requests = Request.where("user_id = ? AND expiration > ?", current_user, Time.now)
    @review = Review.new
  end

  def create
    @request = current_user.requests.new(request_params)
    flash[:notice] = 'Your request has been successfully submitted.' if @request.save
    render json: @request.to_json
    # respond_with(@request)
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.user_id == current_user.id
      @request.update(request_params)
      flash[:notice] = 'Request updated successfully'
    else
      flash[:alert] = 'Only owner can update request'
    end
    redirect_to requests_path
  end

  def destroy
    @request = Request.find(params[:id])
    if @request.user_id == current_user.id
      @request.destroy
      flash[:notice] = 'Request deleted successfully'
    else
      flash[:alert] = 'Only owner can delete request'
    end
    redirect_to requests_path
  end

  private

  def request_params
    params.require(:request).permit(:location, :lat, :lng,
      :description, :budget,
      :disability_access, :children, :luggage, :airport_access,
      :request_date, :tour_duration,
      :time_of_day, :tour_time_start,
      :tour_duration, :tour_time_end, :group_size)
  end

end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/requests_helper.rb
module RequestsHelper

  #Could we put this logic in here rather than in our model? Not sure if the
  #helper modules are meant to be used for the controller only?
  # def set_expiration_date
  #   if self.replies.any?
  #     self.expiration =  Date.today + 1000.days
  #   else
  #     self.expiration =  Date.today + 5.days
  #   end
  # end
  #
  # def build_reply(attributes = {}, user)
  #   attributes[:user] ||= user
  #   replies.build(attributes)
  # end
end

app/views/requests/_form.html.erb
<%= form_for @request do |f| %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br></br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br></br>
  <%= f.label :budget %>
  <%= f.text_area :budget%>
  <br></br>
  <%= f.label :request_date %>
  <%= f.datetime_select :request_date, ampm: true, minute_step: 15 %>
  <br></br>
  <%= f.submit 'Submit' %>
<% end %>

app/views/requests/_modal_request.html.erb
<div id="myModal" class="modal fade" role="dialog" ng-submit="form.update(request, form.request_location)">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Request a tour from a local</h3>
      </div>
      <div class="modal-body">
        <form>
          <div class="essential-fields-wrapper">
            <div class="request-form" id="location_box">
              <label for="location"><h4>Where I'm going: {{form.request_location}}  </h4>*required</label>
              <input type="text" class="form-control" name="location" id="location" ng-model="form.request_location" placeholder="{{form.request_location || 'Where do you want to go?'}}" ng-required="true">
            </div>
            <div class="request-form" id="request_date">
              <label for="request_date"><h4>When I'll be there:  </h4>*required</label>
              <input type="date" class="form-control" name="request_date" id="request_date" ng-model="request.request_date" ng-required="true">
            </div>
            <section class="large-input">
              <div class="request-form" id="radio-time-of-day">
                <h4> I'm free {{request.time_of_day ? request.time_of_day + ', ' : '... ' }} {{(request.request_date | date:'fullDate') || ' ' }}? </h4>
                <fieldset for="request_time_of_day">
                  <label> All day
                    <input class="form-control" type="radio" name="request_time_of_day"  ng-model="request.time_of_day" value="All Day" ng-required="true" checked>
                  </label>
                  <label>Morning
                    <input class="form-control" type="radio" name="request_time_of_day"  ng-model="request.time_of_day" value="Morning" checked>
                  </label>
                  <label> Afternoon
                    <input class="form-control" type="radio" name="request_time_of_day"  ng-model="request.time_of_day" value="Afternoon" checked>
                  </label>
                  <label> Evening
                    <input class="form-control" type="radio" name="request_time_of_day"  ng-model="request.time_of_day" value="Evening" checked>
                  </label>
                </fieldset>
              </div>
              <div class="request-form" id="description-textarea">
                <label for="description"><h4>What I want to do there:  </h4></label>
                <textarea class="form-control" rows="4" name="description" id="description" ng-model="request.description" placeholder="What do you want to do?"></textarea>
              </div>
            </section>
          </div>

          <section class="optional-inputs" ng-show="form.isMoreOptions">
            <aside id="small-inputs1">
              <div class="request-form" id="group_size">
                <label for="group_size"> <h5> Group Size: </h5></label><br>
                  <input type="integer" name="group_size" ng-model="request.group_size" class="form-control" ><br>
              </div>
              <div class="request-form" id="request_budget">
                <label for="budget">
                <h5> I've got {{request.budget ? '£ ' + request.budget : ' a bit '}} to spend </h5>
                </label>
                <!-- <label for="budget"><h5> Budget: </h5></label> -->
                <input type="range" name="budget"
                        min="0" max="250" step="5"
                        class="form-control"
                        id="budget"
                        ng-model="request.budget">
                <!-- <output for="budget" id="request_budget">
                <h5> I've got £{{request.budget || '100'}} to spend </h5>
                </output> -->
              </div>
            </aside>

            <div class="request-form" id="special-considerations">
              <h4> Special Considerations: </h4><br>
              <fieldset for="special_considerations">
                <label>Disabled access required
                  <input class="form-control" type="checkbox" name="special_considerations" ng-model="request.disability_access" value="Disabled" >
                </label>
                <label>Young children in tow
                  <input class="form-control" type="checkbox" name="special_considerations"   ng-model="request.children" value="Children" >
                </label>
                <label>Heavy luggage in tow
                  <input class="form-control" type="checkbox" name="special_considerations"  ng-model="request.luggage" value="Luggage" >
                </label>
                <label>Flying on the same day
                  <input class="form-control" type="checkbox" name="special_considerations" ng-model="request.airport_access" value="FlightsThatDay">
                </label>
              </fieldset>
            </div>

            <h4 id="full-time-free"> I'm free from {{request.tour_time_start | date:'HH' + ':' + 'mm' + ' '}} until {{form.tour_time_end + ' '}} on {{request.request_date | date:'fullDate'}} {{request.tour_duration ? ' for ' + request.tour_duration + ' hours' : ' '}}</h4><br>
            <aside id="small-inputs2">
              <div class="request-form" id="start-time">
                <label for="tour_time_start"><h6>Time start</h6></label>
                <input  class="form-control"
                        type="time"
                        id="tour_time_start"
                        ng-model="request.tour_time_start"
                        >
              </div>
              <div class="request-form" id="duration">
                <label for="time" id="tour_duration">
                  <h6> I've got {{request.tour_duration ? request.tour_duration + ' hours spare' : ' a bit of time spare'}}</h6>
                </label>
                <input  type="range"
                        name="time"
                        class="form-control"
                        value ="2"
                        id="tour_duration"
                        ng-model="request.tour_duration"
                        ng-change="form.calculateTimeLimiter(request.tour_time_start, request.tour_duration)"
                        min="0" max="{{form.calculateTimeLimiter(request.tour_time_start, request.tour_duration) || 12}}" step="1"
                        oninput="form.outputUpdate(value)"
                        >
              </div>
            </aside>

          </section>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" ng-click="form.toggleMoreOptions()" ng-hide="form.isMoreOptions"> More Options </button>
            <button type="button" class="btn btn-default" ng-click="form.toggleMoreOptions()" ng-show="form.isMoreOptions"> Fewer Options </button>
            <button type="submit" class="btn btn-primary" id="modal-submit" >Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/requests/_single_card.html.erb
<div class="col-md-4 col-sm-4">
  <div class="card hovercard">
      <div class="single-cardheader">
        <img src="https://maps.googleapis.com/maps/api/staticmap?zoom=13&size=400x125&maptype=roadmap&center=<%=request.location%>" alt="Card image cap">
      </div>
      <div class="avatar">
        <span class="round-image-50"> <%= image_tag(request.user.avatar.url(:thumb)) %></span>
      </div>
      <div class="info">
          <div class="title">
            <h1> <%= request.user.username %> </h1>
            <div class="stars"><%= average_stars(request.user.average_rating) %> (<%= request.user.reviews.count %>)</div>
              <% if request.group_size %>
              <h4>and <b><%= pluralize(request.group_size, "other") %>
              <% end %>
              <h4> around <%= request.location %></h4>
            <h1>On <b><%= request.request_date.strftime("%B #{request.request_date.day.ordinalize}, %Y")  %></b></h1>
          </div>

          <div class="desc"> Other points to consider for
            <b><%= request.user.f_name %></b></br>
          </div>

          <div class="title"><h4> In their own words...</h4>
            <p><b> <%= request.description %> </b></p></br>
          </div>

          <div class="extra-desc"> They're free <b><%= request.time_of_day == 'All Day' ? request.time_of_day : 'in the ' + request.time_of_day %></b></div>

          <% if request.tour_time_start %>
          <div class="extra-desc"> from <b><%= request.tour_time_start.to_formatted_s(:time) %></b></div>
          <% end %>

          <% if request.tour_duration %>
          <div class="extra-desc"> for <b><%= request.tour_duration.to_i %> hours </b></div>
          <% end %>

          <% if request.budget %>
          <div class="extra-desc">They have <b> £<%= request.budget %> to spend</b> </div>
          <% end %>

            <% if request.luggage %>
            <div class="extra-desc">You find somewhere to store their luggage</div>
            <% end %>

            <% if request.children %>
            <div class="extra-desc">You find a way to entertain their children </div>
            <% end %>

            <% if request.airport_access %>
            <div class="extra-desc">You can get them back to the airport for their flight that day </div>
            <% end %>

            <% if request.disability_access %>
            <div class="extra-desc">You check if all the stop-offs on your tour have disabled access</div>
            <% end %>

          <% if request.expiration %>
          <p class="desc">this request will expire <%= distance_of_time_in_words(Time.now, request.expiration) %> from now </p>
          <% end %>
        </div>
      <% if request.user == current_user %>
        <%= link_to 'Delete', request_path(request), method: :delete, class: 'card-link' %>
        <%= link_to 'Update', edit_request_path(request), class: 'card-link' %>
      <% end %>
  </div>
</div>

app/views/requests/_single_request_info.html.erb
<div class="card hovercard">

    <div class="cardheader">
      <div class="close pull-right" ng-click="r.closeClickedRequestInfo()">&times;</div>
    </div>

    <div class="avatar">
      <img class="img-circle" ng-src="{{r.requestUser.avatar_url}}" alt="Profile picture">
    </div>

    <div class="info">

        <div class="title">
          <h1> {{r.requestUser.f_name}} {{r.requestUser.l_name}}</h1>
          <h3 ng-show="r.clickedRequest.group_size"> ...and {{r.clickedRequest.group_size > 1 ? r.clickedRequest.group_size + ' others' : 'a friend'}}</h3>
          <p> {{ r.clickedRequest.description }} </p>
        </div>

        <div class="desc">
          in<b> {{ r.clickedRequest.location }} </b>
        </div>

        <div class="desc">
          On
          <b>
            {{r.clickedRequest.request_date | date:'fullDate'}}
          </b>
        </div>

        <h4> Other details to bear in mind: </h4>

        <div class="desc" ng-show="r.clickedRequest.budget">
          {{r.requestUser.f_name}} has <b> £{{r.clickedRequest.budget}}</b> to spend
        </div>

        <div class="desc">
          <h5> {{r.requestUser.f_name}}'s availability:
            <b>{{ r.clickedRequest.time_of_day === 'All Day' ? 'All Day' : 'in the ' + r.clickedRequest.time_of_day}}</b>
          </h5>

          <h5 ng-show="r.clickedRequest.duration">and is available for
            <b>{{r.clickedRequest.duration}} hours</b>
          </h5>

          <h5 ng-show="r.clickedRequest.tour_time_start">
            From:  {{r.clickedRequest.tour_time_start | date:'HH:mm'}}
          </h5>

          <h5 ng-show="r.clickedRequest.luggage">
            {{r.requestUser.f_name}} has
            <b> heavy luggage in tow</b>
          </h5>

          <h5 ng-show="r.clickedRequest.children">
            {{r.requestUser.f_name}} has
            <b> children who will be on the tour </b>
          </h5>

          <h5 ng-show="r.clickedRequest.airport_access">
            {{r.requestUser.f_name}} has
            <b> to be able to get to the airport </b>
          </h5>
          <h5 ng-show="r.clickedRequest.disability_access">
            {{r.requestUser.f_name}} needs
            <b> disability access </b>
          </h5>

        <h3> Think you can help <b>{{r.requestUser.f_name}}</b> ? </h3>

    </div>

    <div class="bottom" ng-show="r.requestUser.id !== map.current_user.id">
      <a ng-href="/requests/{{r.clickedRequest.id}}/replies/new"><button class="btn-for-request">Reply to {{r.requestUser.f_name}}'s request</button></a>
      <a ng-href="/profile/{{r.requestUser.id}}" target="_blank"><button class="btn-for-request">Find out more about {{r.requestUser.f_name}}</button></a>
    </div>

</div>

app/views/requests/edit.html.erb
<%= render "form" %>

app/views/requests/index.html.erb
<% if @requests.any? %>
  <div class="container comment-list">
    <% @requests.each do |request| %>
      <div class="row">

        <%= render 'single_card', request: request %>

          <div class="col-md-7 col-sm-7">
            <% request.replies.each do |reply| %>
              <%= render 'replies/single_reply', request: request, reply: reply %>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
<% else %>
  <p> You have not made any requests yet. </p>
<% end %>

app/views/requests/new.html.erb
<%= render "form" %>