config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'api/users' => 'users#index'
  get 'api/c_user' => 'users#c_user'
  get 'api/reply/:id' => 'replies#c_reply'
  get 'replies' => 'replies#index'
  get "profile/:id"=> "users#profile"

  resources :requests do
    resources :replies do
      post :choose, on: :member
      resources :reviews
    end
  end

end

app/views/layouts/_autocomplete_search.html.erb
  <div layout="column" ng-cloak>
      <md-content class="md-padding">
        <form>
            <md-autocomplete
                id="autocompletebox"
                md-search-text="form.searchText"
                md-no-cache="true"
                md-search-text-change="form.autoCompleteSearch(form.searchText)"
                md-input-name="form.autocompleteSuggestions"
                md-selected-item="form.selectedItem"
                md-selected-item-change="form.moveHere(form.searchText)"
                md-items="item in form.autocompleteSuggestions"
                md-item-text="item.description"
                md-input-minlength="0">

            <md-item-template>
                <span md-highlight-text="form.searchText" md-highlight-flags="^i"> {{item.description}} </span>
            </md-item-template>
          </md-autocomplete>
        </form>
      </md-content>
    </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">localknowledge</a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
           <% if current_user %>
             <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
             <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

             <li><a href="#" data-toggle="modal" data-target="#myModal">Request a tour</a></li>

             <li><%= link_to 'My requests', requests_path %></li>
             <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
           <% else %>
            <li><a href="#" data-toggle="modal" data-target="#loginModal">Login</a></li>
            <li><a href="#" data-toggle="modal" data-target="#signUpModal">Sign Up</a></li>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="/">
        LocalHost:
      </a>
    </li>
    <% if current_user %>
      <section class="top-section">
            <hr>
        <ul class="list-inline">
          <li>
            <a href="/profile/<%=current_user.id%>">
              <p><%= image_tag(current_user.avatar.url(:thumb), { class: 'img-circle'})%><p> </li>
            </a>
          <li> <h4 class="username"><%= current_user.f_name %> <%= current_user.l_name %></h4> </li>
        </ul>
        <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
        <hr>
      </section>
      <% if current_page?(controller: '/home', action: 'index') %>
        <li><a href="#" data-toggle="modal" data-target="#myModal">Request a tour</a></li>
      <% else %>
        <li><%= link_to 'Request a tour', root_url %></li>
      <% end %>
      <li><%= link_to 'My requests', requests_path %></li>
      <li><%= link_to 'My replies', replies_path %></li>
    <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="LocalKnowledgeApp">
<head>
  <title>LocalHost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places,geometry" async defer></script>
</head>
<body>

    <%= flash_messages %>

    <% if user_signed_in? %>
      <div id="wrapper">
        <%= render "layouts/sidebar" %>
        <% unless current_user %>
          <%= render "devise/sessions/login" %>
          <%= render "devise/registrations/signup" if controller_name != 'registrations' %>
        <% end %>
        <div id="page-content-wrapper">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <% unless current_user %>
        <%= render "devise/sessions/login" %>
        <%= render "devise/registrations/signup" if controller_name != 'registrations' %>
      <% end %>
      <%= yield %>
    <% end %>

</body>
</html>